apiVersion: batch/v1
kind: Job
metadata:
  name: backup
spec:
  template:
    spec:
      containers:
      - name: backup
        image: busybox:1.28
        command: ["echo", "Starting Backup..."]
      restartPolicy: Never