apiVersion: batch/v1
kind: Job
metadata:
  name: backup
spec:
  template:
    spec:
      containers:
      - name: backup
        image: alpine
        imagePullPolicy: IfNotPresent
        command: 
        - echo Starting Backup...
        - sleep 5
        - echo Backup done!
      restartPolicy: Never
