apiVersion: batch/v1
kind: Job
metadata:
  name: backup
spec:
  template:
    spec:
      containers:
      - name: backup
        image: alpine
        command: echo Starting Backup...
      restartPolicy: Never