apiVersion: batch/v1
kind: Job
metadata:
  name: backup
spec:
  template:
    spec:
      containers:
      - name: backup
        image: alpine
        command: 
        - echo Starting Backup...
        - wget https://raw.githubusercontent.com/ar-do/vcnt/main/backup_source/backup_file.txt
        - git clone https://github.com/ar-do/vcnt_demo backup_dest
        - cp jobs/backup_source/backup_file.txt backup_dest/
        - git push -u origin main
        - echo Backup done
      restartPolicy: Never