apiVersion: batch/v1
kind: Job
metadata:
  name: backup
spec:
  template:
    spec:
      containers:
      - name: backup
        image: ubuntu:latest
        imagePullPolicy: IfNotPresent
        command: 
        - echo Starting Backup...
        - apt-get -y update
        - apt-get -y install wget
        - wget https://raw.githubusercontent.com/ar-do/vcnt/main/jobs/backup_source/backup_file.txt
        - sleep 5
        - echo Backup done!
      restartPolicy: Never